apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.kafka.host . }}
spec:
  type: ClusterIP
  selector:
     app: kafka
  ports:
  - port: 9092
    protocol: TCP


{{ if .Values.debug }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.elasticApmServer.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 8200
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.elasticsearch.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 9200
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.kibana.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 5601
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.pgadmin.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 8080
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.redisCommander.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 8081
    protocol: TCP

{{ end }}
