{{- if .Values.kafka.controller.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "digma.kafka.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kafka
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.kafka.controller.pdb.minAvailable }}
  minAvailable: {{ .Values.kafka.controller.pdb.minAvailable }}
  {{- end  }}
  {{- if .Values.kafka.controller.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.kafka.controller.pdb.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka
{{- end }}
