apiVersion: v1
kind: Service
metadata:
  name: {{ include "digma.otel-collector" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  {{- if or .Values.otelCollector.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.otelCollector.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.otelCollector.service.type }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.otelCollector.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
  - name: health
    protocol: TCP
    port: {{ .Values.otelCollector.service.ports.health }}
  {{- if .Values.otelCollector.service.ports.http }}
  - name: http
    protocol: TCP
    port: {{ .Values.otelCollector.service.ports.http }}
  {{- end }}
  {{- if .Values.otelCollector.service.ports.grpc }}
  - name: grpc
    protocol: TCP
    port: {{ .Values.otelCollector.service.ports.grpc }}
  {{- end }}