apiVersion: v2
name: digma
description: A Helm chart containing Digma's services and dbs
home: https://github.com/digma-ai/digma
icon: https://github.com/digma-ai/digma/raw/main/images/digma_logo_wingz.png
type: application
version: "0.1.13"
appVersion: "0.1.13"
