apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-analytics-deployment
  labels:
    app: digma-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-analytics
  template:
    metadata:
      labels:
        app: digma-analytics
    spec:
      containers:
      - name: digma-analytics
        image: digmatic/digma-analytics:{{ .Chart.AppVersion }}
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: {{ .Values.digmaAnalytics.cpuLimit }}
        ports:
        - containerPort: 5052
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.rabbit" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ApplicationVersion={{.Chart.AppVersion}}


