apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-analytics-deployment
  labels:
    app: digma-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digma-analytics
  template:
    metadata:
      labels:
        app: digma-analytics
    spec:
      containers:
      - name: digma-analytics
        image: digmatic/digma-analytics:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaAnalytics.resources.requests.memory }}
            cpu: {{ .Values.digmaAnalytics.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaAnalytics.resources.limits.memory }}
            cpu: {{ .Values.digmaAnalytics.resources.limits.cpu }}
        ports:
        - containerPort: 5052
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ApplicationVersion={{.Chart.AppVersion}},ChartVersion={{.Chart.Version}}


