apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-collector-deployment
  labels:
    app: digma-collector-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-collector-api
  template:
    metadata:
      labels:
        app: digma-collector-api
    spec:
      containers:
      - name: digma-collector-api
        image: digmatic/digma-collector:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 5049
        - containerPort: 5050
        - containerPort: 5060
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: {{ .Values.digmaCollectorApi.cpuLimit }}
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.rabbit" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ApplicationVersion={{.Chart.AppVersion}}