apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-digma-pipeline-worker-deployment
  labels:
    app: digma-pipeline-worker
spec:
  replicas: {{ tpl .Values.digmaPipelineWorker.replicas . }}
  selector:
    matchLabels:
      app: digma-pipeline-worker
  template:
    metadata:
      labels:
        app: digma-pipeline-worker
    spec:
      containers:
      - name: digma-pipeline-worker
        image: digmatic/digma-pipeline-worker:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaPipelineWorker.resources.requests.memory }}
            cpu: {{ .Values.digmaPipelineWorker.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaPipelineWorker.resources.limits.memory }}
            cpu: {{ .Values.digmaPipelineWorker.resources.limits.cpu }}
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.otlpExportLogs" . | nindent  8 }}
        {{- include "env.otlpExportMetrics" . | nindent  8 }}
        {{- include "env.otlpExportTraces" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.kafka" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
        {{- include "env.embeddedJaeger" . | nindent 8 }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: BACKEND_DEPLOYMENT_TYPE
          value: {{ .Values.deploymentType | quote }}
        - name: Ds__Url
          value: {{ printf "http://%s:5054" (tpl .Values.digmaDs.host .) }}