apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-digma-scheduler-deployment
  labels:
    app: digma-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-scheduler
  template:
    metadata:
      labels:
        app: digma-scheduler
    spec:
      containers:
      - name: digma-scheduler
        image: digmatic/digma-scheduler:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaScheduler.resources.requests.memory }}
            cpu: {{ .Values.digmaScheduler.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaScheduler.resources.limits.memory }}
            cpu: {{ .Values.digmaScheduler.resources.limits.cpu }}
        ports:
        - containerPort: 5053
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.rabbit" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ApplicationVersion={{.Chart.AppVersion}}


