apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ds-deployment
  labels:
    app: digma-ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-ds
  template:
    metadata:
      labels:
        app: digma-ds
    spec:
      containers:
      - name: digma-ds
        image: digmatic/ds:{{ .Values.digmaDs.imageTag }}
        command: ["gunicorn", "-w 4", "--statsd-host=statsd-exporter:9125", "-b 0.0.0.0:5054", "app.main:app"]
        resources:
          requests:
            memory: {{ .Values.digmaDs.resources.requests.memory }}
            cpu: {{ .Values.digmaDs.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaDs.resources.limits.memory }}
            cpu: {{ .Values.digmaDs.resources.limits.cpu }}
        ports:
        - containerPort: 5054
        env:
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: {{ .Values.digmaSelfDiagnosis.otlpExporterEndpoint }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ printf "digma.environment=%s" .Values.digma.environmentName }}
        # - name: OTEL_TRACES_SAMPLER
        #   value: traceidratio
        # - name: OTEL_TRACES_SAMPLER_ARG
        #   value:  {{ quote .Values.digmaSelfDiagnosis.otlpSamplerProbability }}
