apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-digma-collector-worker-deployment
  labels:
    app: digma-collector-worker
spec:
  replicas: {{ tpl .Values.digmaCollectorWorker.replicas . }}
  selector:
    matchLabels:
      app: digma-collector-worker
  template:
    metadata:
      labels:
        app: digma-collector-worker
    spec:
      containers:
      - name: digma-collector-worker
        image: digmatic/digma-collector-worker:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaCollectorWorker.resources.requests.memory }}
            cpu: {{ .Values.digmaCollectorWorker.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaCollectorWorker.resources.limits.memory }}
            cpu: {{ .Values.digmaCollectorWorker.resources.limits.cpu }}
        env:
        - name: IsCentralize
          value: {{ .Values.digma.isCentralize }}
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.otlpExportLogs" . | nindent  8 }}
        {{- include "env.otlpExportMetrics" . | nindent  8 }}
        {{- include "env.otlpExportTraces" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.kafka" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
        {{- include "env.embeddedJaeger" . | nindent  8 }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: BACKEND_DEPLOYMENT_TYPE
          value: {{ .Values.deploymentType | quote}}
        - name: ThresholdOptions__RecentActivityUpdateThresholdSeconds
          value: {{ .Values.traceCollectorThresholds.recentActivityUpdateThresholdSeconds | quote }}
        - name: ThresholdOptions__UpsertEndpointThresholdSeconds
          value: {{ .Values.traceCollectorThresholds.upsertEndpointThresholdSeconds | quote }}
        - name: ThresholdOptions__UpsertSpansThresholdSeconds
          value: {{ .Values.traceCollectorThresholds.upsertSpansThresholdSeconds | quote }}
        - name: ThresholdOptions__UpsertSpanFlowMetadataThresholdSeconds
          value: {{ .Values.traceCollectorThresholds.upsertSpanFlowMetadataThresholdSeconds | quote }}
