apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-analytics-deployment
  labels:
    app: digma-analytics
spec:
  replicas: {{ .Values.digmaAnalytics.replicas }}
  selector:
    matchLabels:
      app: digma-analytics
  template:
    metadata:
      labels:
        app: digma-analytics
        {{- range $key, $value := .Values.digmaAnalytics.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.digmaAnalytics.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent  6 }}
      containers:
      - name: digma-analytics
        image: digmatic/digma-analytics:{{ .Chart.AppVersion }}
        
        resources:
          requests:
            memory: {{ .Values.digmaAnalytics.resources.requests.memory }}
            cpu: {{ .Values.digmaAnalytics.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaAnalytics.resources.limits.memory }}
            cpu: {{ .Values.digmaAnalytics.resources.limits.cpu }}
        ports:
        - containerPort: 5051
        env:
        {{- include "env.isCentralize" . | nindent  8 }}
        {{- include "env.licenseKey" . | nindent  8 }}
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.kafka" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.otlpExportLogs" . | nindent  8 }}
        {{- include "env.otlpExportMetrics" . | nindent  8 }}
        {{- include "env.otlpExportTraces" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
        {{- include "env.digmaEnvType" . | nindent 8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote }}
        - name: BACKEND_DEPLOYMENT_TYPE
          value: {{ .Values.deploymentType | quote }}
        - name: GlobalExceptionSettings__ExposeInternalDetails
          value: {{ .Values.exposeInternalErrorDetails | quote }}
        - name: AccessToken
          value: {{ .Values.digmaAnalytics.accesstoken | quote }}
        - name: Analytics.Endpoints__Default__Secured
          value: {{ .Values.digmaAnalytics.secured | quote }}
        - name: CollectorUrl
          value: {{ printf " http://%s:5048" (tpl .Values.digmaCollectorApi.host .)}}


