apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler-deployment
  labels:
    app: digma-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-scheduler
  template:
    metadata:
      labels:
        app: digma-scheduler
        {{- range $key, $value := .Values.digmaScheduler.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.digmaScheduler.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent  6 }}
      {{- include "tolerations" . | nindent  6 }}
      {{- include "nodeSelector" . | nindent  6 }}
      imagePullPolicy: always
      containers:
      - name: digma-scheduler
        image: digmatic/digma-scheduler:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaScheduler.resources.requests.memory }}
            cpu: {{ .Values.digmaScheduler.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaScheduler.resources.limits.memory }}
            cpu: {{ .Values.digmaScheduler.resources.limits.cpu }}
        ports:
        - containerPort: 5053
        env:
        {{- include "env.isCentralize" . | nindent  8 }}
        {{- include "env.licenseKey" . | nindent  8 }}
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.kafka" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.otlpExportLogs" . | nindent  8 }}
        {{- include "env.otlpExportMetrics" . | nindent  8 }}
        {{- include "env.otlpExportTraces" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
        {{- include "env.digmaEnvType" . | nindent 8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: BACKEND_DEPLOYMENT_TYPE
          value: {{ .Values.deploymentType | quote}}
{{- if eq .Values.embeddedJaeger.storage "elasticsearch" }}
        - name: ElasticSearch__Uri
          value: http://{{ .Release.Name }}-elasticsearch:9200
{{- end }}  


