apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-collector-deployment
  labels:
    app: digma-collector-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-collector-api
  template:
    metadata:
      labels:
        app: digma-collector-api
        {{- range $key, $value := .Values.digmaCollectorApi.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.digmaCollectorApi.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent  6 }}
      imagePullPolicy: always
      containers:
      - name: digma-collector-api
        image: digmatic/digma-collector:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaCollectorApi.resources.requests.memory }}
            cpu: {{ .Values.digmaCollectorApi.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaCollectorApi.resources.limits.memory }}
            cpu: {{ .Values.digmaCollectorApi.resources.limits.cpu }}
        ports:
        - containerPort: 5048
        - containerPort: 5049
        - containerPort: 5050
        env:
        {{- include "env.isCentralize" . | nindent  8 }}
        {{- include "env.licenseKey" . | nindent  8 }}
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.kafka" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.otlpExportLogs" . | nindent  8 }}
        {{- include "env.otlpExportMetrics" . | nindent  8 }}
        {{- include "env.otlpExportTraces" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
        {{- include "env.embeddedJaeger" . | nindent  8 }}
        {{- include "env.digmaEnvType" . | nindent 8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: BACKEND_DEPLOYMENT_TYPE
          value: {{ .Values.deploymentType | quote}}
