{{ if .Values.embeddedJaeger.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-embedded-jaeger
  labels:
    app: embedded-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedded-jaeger
  template:
    metadata:
      labels:
        app: embedded-jaeger
    spec:
      containers:
      - name: embedded-jaeger
        image: jaegertracing/all-in-one:{{ .Values.embeddedJaeger.imageTag }}
        args:
          - "--query.additional-headers=Access-Control-Allow-Origin: *"
        env:
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        - name: ES_SERVER_URLS
          value: "http://{{ .Release.Name }}-elasticsearch:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_OTLP_GRPC_MAX_MESSAGE_SIZE
          value: "41943040"
          resources:
            requests:
              memory: "{{ .Values.embeddedJaeger.resources.requests.memory }}"
              cpu: "{{ .Values.embeddedJaeger.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.embeddedJaeger.resources.limits.memory }}"
              cpu: "{{ .Values.embeddedJaeger.resources.limits.cpu }}"
{{ end }}
