{{ if .Values.embeddedJaeger.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-embedded-jaeger
  labels:
    app: embedded-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedded-jaeger
  serviceName: {{ tpl .Values.embeddedJaeger.host . }}
  template:
    metadata:
      labels:
        app: embedded-jaeger
    spec:
      terminationGracePeriodSeconds: 5
      {{- include "imagePullSecrets" . | nindent  6 }}
      containers:
      - name: embedded-jaeger
        image: jaegertracing/all-in-one:{{ .Values.embeddedJaeger.imageTag }}
        args: ["--query.additional-headers", "Access-Control-Allow-Origin: *"]
        env:
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        - name: ES_SERVER_URLS
          value: "http://{{ .Release.Name }}-elasticsearch:9200"
        - name: ES_INDEX_PREFIX
          value: "digma"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_OTLP_GRPC_MAX_MESSAGE_SIZE
          value: "41943040"
{{ end }}
