# Analytics Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-analytics-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: "digma-analytics"
  ports:
    - name: analytics
      protocol: TCP
      port: 5051
      targetPort: 5051

---

# Collector API Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-collector-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: "digma-collector-api"
  ports:
    - name: http
      protocol: TCP
      port: 5049
      targetPort: 5049
    - name: grpc
      protocol: TCP
      port: 5050
      targetPort: 5050

---

# Jaeger Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-embedded-jaeger
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: "embedded-jaeger"
  ports:
    - name: jaeger-api
      port: 16686
      protocol: TCP
      targetPort: 16686

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
  
---

# Ingress Resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.{{ .Values.ingressController.host }}
        - jaeger.{{ .Values.ingressController.host }}
        - collector.{{ .Values.ingressController.host }}
      secretName: {{ .Release.Name }}-tls-secret
  rules:
    - host: jaeger.{{ .Values.ingressController.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-embedded-jaeger
                port:
                  number: 16686
    - host: api.{{ .Values.ingressController.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-analytics-service
                port:
                  number: 5051
    - host: collector.{{ .Values.ingressController.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-collector-api-service
                port:
                  number: 5049