{{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-grafana-stateful-set
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  serviceName: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: init-grafana
        image: busybox:1.28
        command:
        - 'sh', 
        - '-c', 
        - "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"
 
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_USERS_ALLOW_SIGN_UP
          value: false
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
          subPath: grafana-data

  volumeClaimTemplates:
  - metadata:
      name: grafana-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
---

{{- end }}