{{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  serviceName: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-provisioning
        emptyDir: {}
      - name: grafana-dashboards
        emptyDir: {}
      initContainers:
      - name: init-grafana
        image: alpine/git:2.45.2
        command:
        - 'sh'
        - '-c'
        - |
          git clone -b local-prom-grafana https://github.com/digma-ai/helm-chart;
          cd helm-chart/src/digma/grafana-config;

          mkdir -p /var/lib/grafana/dashboards;
          mkdir -p /etc/grafana/provisioning/dashboards;
          mkdir -p /etc/grafana/provisioning/datasources;

          cp -r dashboards/* /var/lib/grafana/dashboards/;
          cp dashboard.yaml /etc/grafana/provisioning/dashboards/main.yaml;
          cp datasource.yaml /etc/grafana/provisioning/datasources/main.yaml;

          echo 'Finished setting grafana config files'
        volumeMounts:
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards

      containers:
      - name: grafana
        image: grafana/grafana:10.3.3
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_USERS_ALLOW_SIGN_UP
          value: 'false'
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    protocol: TCP

{{- end }}