apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-influxdb-stateful-set
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: {{ tpl .Values.influx.host . }}
  {{ if .Release.IsInstall }}
  minReadySeconds: 5
  {{ end }}
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: influxdb
        image: influxdb:{{ .Values.influx.imageTag }}
        ports:
          - containerPort: 8086
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "admin"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "12345678"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "digma"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "errors"
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: "24w"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "dc61908e-05bc-411a-9fe2-e3356b8dc7c0"
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb2
        - name: influxdb-data
          mountPath: /etc/influxdb2
  volumeClaimTemplates:
    - metadata:
        name: influxdb-data
      spec:
        storageClassName: gp2
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 80Gi
  # persistentVolumeClaimRetentionPolicy:
  #   whenDeleted: Retain
