apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.kafka.host . }}
spec:
  type: ClusterIP
  selector:
     app: kafka
  ports:
  - port: 9092
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.postgres.host . }}
spec:
  type: ClusterIP
  selector:
    app: "postgres"
  ports:
  - port: {{ .Values.postgres.port }}
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.redis.host . }}
spec:
  type: ClusterIP
  selector:
    app: "redis"
  ports:
  - port: 6379
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.influx.host . }}
spec:
  type: ClusterIP
  selector:
    app: "influxdb"
  ports:
  - port: 8086
    protocol: TCP
      
---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.digmaAnalytics.host . }}
spec:
  type: ClusterIP
  selector:
    app: digma-analytics
  ports:
  - port: 5051
    protocol: TCP 

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.digmaScheduler.host . }}
spec:
  type: ClusterIP
  selector:
    app: "digma-scheduler"   
  ports:
  - port: 5053
    protocol: TCP 

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.digmaCollectorApi.host . }}
spec:
  type: ClusterIP
  selector:
     app: "digma-collector-api"
  ports:
    - name: internal
      protocol: TCP
      port: 5048
    - name: http
      protocol: TCP
      port: 5049
    - name: grpc
      protocol: TCP
      port: 5050


{{ if .Values.embeddedJaeger.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.embeddedJaeger.host . }}
spec:
  type: ClusterIP
  selector:
     app: "embedded-jaeger"
  ports:
  - name: grpc
    port: 4317
    protocol: TCP
  - name: api
    port: 16686
    protocol: TCP

{{ end }}


{{ if .Values.debug }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.elasticApmServer.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 8200
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.elasticsearch.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 9200
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.kibana.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 5601
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.pgadmin.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 8080
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.redisCommander.host . }}
spec:
  selector:
    app: "digma-debug-services"
  ports:
  - port: 8081
    protocol: TCP

{{ end }}
