apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kafka-stateful-set
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: {{ tpl .Values.kafka.host . }}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: kafka
        image: bitnami/kafka:{{ .Values.kafka.imageTag }}
        resources:
          requests:
            memory: {{ .Values.kafka.resources.requests.memory }}
            cpu: {{ .Values.kafka.resources.requests.cpu }}
          limits:
            memory: {{ .Values.kafka.resources.limits.memory }}
            cpu: {{ .Values.kafka.resources.limits.cpu }}
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "1"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: h4U35I9QRnGhbgsEQAlXAw
        # Start Kraft Setup (Kafka as Controller - no Zookeeper)
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@127.0.0.1:9093
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_LOG_DIRS
          value: tmp/logs
        - name: KAFKA_CFG_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093
        # End Kraft Specific Setup
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://{{ tpl .Values.kafka.host . }}:9092
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi


