apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kafka-stateful-set
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: {{ tpl .Values.kafka.host . }}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1001
      containers:
      - name: kafka
        image: bitnami/kafka:{{ .Values.kafka.imageTag }}
        resources:
          requests:
            memory: {{ .Values.kafka.resources.requests.memory }}
            cpu: {{ .Values.kafka.resources.requests.cpu }}
          limits:
            memory: {{ .Values.kafka.resources.limits.memory }}
            cpu: {{ .Values.kafka.resources.limits.cpu }}
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
        env:
        # KRaft settings
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: h4U35I9QRnGhbgsEQAlXAw
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: controller,broker
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@127.0.0.1:9093
        # Listeners
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        # Retention
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "1"
        - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS
          value: "300000"
        - name: KAFKA_CFG_LOG_ROLL_HOURS
          value: "1"
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi


