{{- if .Values.digmaSelfDiagnosis.otlpExporterEndpoint }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
data:
  key-collector-yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
      kafkametrics:
        protocol_version: 2.0.0
        collection_interval: 10s
        brokers: [{{ printf "%s:9092" (tpl .Values.kafka.host .)}}]
        scrapers:
          - brokers
          - topics
          - consumers
      prometheus/k8s_metrics:
        config:
          scrape_configs:
            - job_name: k8s-metrics
              scrape_interval: 5s
              static_configs:
                - targets: [{{ printf "%s-k8s-metrics-exporter:9090" (.Release.Name)}}]

    processors:
      batch:
      attributes/add_source_env:
        actions:
          - key: source_env
            value: {{.Values.digma.environmentName}}
            action: insert

    exporters:
      logging:
        verbosity: detailed
      {{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}
      prometheus:
        endpoint: 0.0.0.0:7777
        send_timestamps: true
        metric_expiration: 10m
      {{- else }}
      otlp:
        endpoint: {{.Values.digmaSelfDiagnosis.otlpExporterEndpoint}}
      {{- end }}

    service:
      pipelines:
        {{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}
        metrics:
          receivers: [otlp, kafkametrics, prometheus/k8s_metrics]
          processors: [attributes/add_source_env, batch]
          exporters: [prometheus]
        {{- else }}
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp, kafkametrics, prometheus/k8s_metrics]
          processors: [attributes/add_source_env, batch]
          exporters: [otlp]
        {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otel-collector-df-deployment
  labels:
    app: otel-collector-df
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-df
  template:
    metadata:
      labels:
        app: otel-collector-df
    spec:
      {{- include "imagePullSecrets" . | nindent  6 }}
      containers:
        - name: otel-collector-df
          image: otel/opentelemetry-collector-contrib:0.103.0
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 300Mi
          ports:
            - containerPort: 4317
          args:
            - --config=/conf/collector.yaml
          volumeMounts:
            - name: vn-config
              mountPath: /conf
              readOnly: true
      volumes:
        - name: vn-config # volume name
          configMap:
            name: {{ .Release.Name }}-otel-collector-config # configMap name
            items:
              - key: "key-collector-yaml"
                path: "collector.yaml"
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector
spec:
  selector:
    app: otel-collector-df
  ports:
  - name: grpc-port
    port: 4317
    protocol: TCP
  - name: debug
    port: 7777

{{- end -}}