apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-plugin-api-deployment
  labels:
    app: digma-plugin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digma-plugin-api
  template:
    metadata:
      labels:
        app: digma-plugin-api
    spec:
      containers:
      - name: digma-plugin-api
        image: digmatic/digma-plugin-api:{{ .Chart.AppVersion }}
        resources:
          requests:
            memory: {{ .Values.digmaPluginApi.resources.requests.memory }}
            cpu: {{ .Values.digmaPluginApi.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaPluginApi.resources.limits.memory }}
            cpu: {{ .Values.digmaPluginApi.resources.limits.cpu }}
        ports:
        - containerPort: 5051
        env:
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
{{ if .Values.debug }}
        {{- include "env.elasticsearch" . | nindent  8 }}
{{ end }}
        - name: AnalyticsUrl
          value: {{ printf " http://%s:5052" (tpl .Values.digmaAnalytics.host .)}}
        - name: AccessToken
          value: {{ required "A valid .Values.digmaPluginApi.accesstoken entry is required." .Values.digmaPluginApi.accesstoken }}
        - name: Secured
          value: {{ .Values.digmaPluginApi.secured | quote }}
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: ApplicationVersion={{.Chart.AppVersion}}