apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres-stateful-set
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: {{ tpl .Values.postgres.host . }}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: postgres
        image: postgres:{{ .Values.postgres.imageTag }}
        resources:
          requests:
            memory: {{ .Values.postgres.resources.requests.memory }}
            cpu: {{ .Values.postgres.resources.requests.cpu }}
          limits:
            memory: {{ .Values.postgres.resources.limits.memory }}
            cpu: {{ .Values.postgres.resources.limits.cpu }}
        ports:
          - containerPort: 5432
        args:
          - "-c"
          - "max_connections={{ .Values.postgres.maxConnections }}"
          - "-c"
          - "shared_buffers={{ .Values.postgres.sharedBuffers }}"
          - "-c"
          - "logging_collector={{ .Values.postgres.loggingCollector }}"
          - "-c"
          - "log_directory=log"
        env:
        - name: POSTGRES_NAME
          value: postgres
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "800Mi"  
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  # persistentVolumeClaimRetentionPolicy:
  #   whenDeleted: Retain
