{{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
data:
  prometheus-yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: otel-collector
        static_configs:
          - targets: [{{ printf "%s-otel-collector:7777" (.Release.Name)}}]
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-prometheus-stateful-set
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  serviceName: {{ .Release.Name }}-prometheus
  template:
    metadata:
      labels:
        app: prometheus
        {{- range $key, $value := .Values.prometheus.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.prometheus.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: 2000 
      {{- include "imagePullSecrets" . | nindent  6 }}
      {{- include "tolerations" . | nindent  6 }}
      {{- include "nodeSelector" . | nindent  6 }}
      imagePullPolicy: always
      containers:
      - name: prometheus
        image: prom/prometheus:v2.53.0
        args:
        - '--storage.tsdb.path=/prometheus'
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
        {{- range .Values.prometheus.args }}
        - {{ . }}
        {{- end }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
          subPath: prometheus-db
        - name: prometheus-config
          mountPath: /etc/prometheus/
          readOnly: true
      volumes:
      - name: prometheus-config
        configMap:
          name: {{ .Release.Name }}-prometheus-config
          items:
          - key: "prometheus-yml"
            path: "prometheus.yml"
      # - name: prometheus-data
      #   emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
---

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.prometheus.host . }}
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    protocol: TCP

{{- end }}