apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbit.username}}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbit.password}}
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq/
        - name: rabbitmq-log
          mountPath: /var/log/rabbitmq/
        ports:
        - containerPort: 5672
        - containerPort: 15672
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
      - name: rabbitmq-log
        emptyDir: {}

     
     
