apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis-stateful-set
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: {{ tpl .Values.redis.host . }}
  template:
    metadata:
      labels:
        app: redis
        {{- range $key, $value := .Values.redis.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.redis.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 5
      {{- include "imagePullSecrets" . | nindent  6 }}
      {{- include "tolerations" . | nindent  6 }}
      {{- include "nodeSelector" . | nindent  6 }}
      imagePullPolicy: always
      containers:
        - name: redis
          image: redis:{{ .Values.redis.imageTag }}
          args:
            - "--maxmemory {{ .Values.redis.config.maxmemory }}"
            - "--maxmemory-policy {{ .Values.redis.config.maxmemoryPolicy }}"
            {{- range .Values.redis.args }}
            - {{ . }}
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command:
            - "redis-server"
           
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  # persistentVolumeClaimRetentionPolicy:
  #   whenDeleted: Retain
