apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui-service
  labels:
    app: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: "{{ .Values.uiService.image.repository }}:{{ .Values.uiService.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.uiService.resources | nindent 12 }}
          
---
  
