apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digma.analytics-api.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: analytics-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.digma.accessToken }}
  {{ include "digma.analytics-api.accessToken.secretKeyName" .}}: {{ .Values.digma.accessToken | b64enc }}
  {{- end }}
  {{- if .Values.digma.socialLogin.google.secret }}
  {{ include "digma.analytics-api.socialLoginGoogleSecret.secretKeyName" .}}: {{ .Values.digma.socialLogin.google.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.digma.auth.password }}
  {{ include "digma.analytics-api.authPassword.secretKeyName" .}}: {{ .Values.digma.auth.password | b64enc | quote }}
  {{- end }}