{{- if eq "true" (include "digma.observability.enabled" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digma.otel-collector-df" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-collector-df
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml:
    {{- include "common.tplvalues.render" (dict "value" .Values.otelCollectorDf.configuration "context" $) | toYaml | nindent 4 }}
{{- end }}