{{- if not .Values.otelCollector.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digma.otel-collector" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data: # config.yaml:
  config.yaml:
    {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.configuration "context" $) | toYaml | nindent 4 }}
{{- end }}