#
# exposing otel-collector-df
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector-df-service
spec:
  type: LoadBalancer
  selector:
    app: "otel-collector-df"
  ports:
    - name: collector-otlp
      protocol: TCP
      port: 4317
      targetPort: 4317

{{ if .Values.digmaPluginApi.expose }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-digma-plugin-api-service
spec:
  type: LoadBalancer
  selector:
     app: "digma-plugin-api"
  ports:
    - name: plugin-api
      protocol: TCP
      port: 5051

{{ end }}
