{{ if .Values.digmaPluginApi.expose }}

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-plugin-api-service-lb
spec:
  type: LoadBalancer
  selector:
     app: "digma-plugin-api"
  ports:
    - name: plugin-api
      protocol: TCP
      port: 5051

{{ end }}

{{ if .Values.digmaCollectorApi.expose }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-collector-api-service-lb
spec:
  type: LoadBalancer
  selector:
     app: "digma-collector-api"
  ports:
    - name: http
      protocol: TCP
      port: 5049
    - name: grpc
      protocol: TCP
      port: 5050

{{ end }}
