apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-collector-worker-deployment
  labels:
    app: digma-collector-worker
spec:
  replicas: {{ tpl .Values.digmaCollectorWorker.replicas . }}
  selector:
    matchLabels:
      app: digma-collector-worker
  template:
    metadata:
      labels:
        app: digma-collector-worker
        {{- range $key, $value := .Values.digmaCollectorWorker.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.digmaCollectorWorker.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent  6 }}
      {{- include "tolerations" . | nindent  6 }}
      {{- include "nodeSelector" . | nindent  6 }}
      affinity:
        {{- toYaml .Values.digmaCollectorWorker.affinity | nindent 8 }}
      containers:
      - name: digma-collector-worker
        image: digmatic/digma-collector-worker:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.digmaCollectorWorker.resources.requests.memory }}
            cpu: {{ .Values.digmaCollectorWorker.resources.requests.cpu }}
          limits:
            memory: {{ .Values.digmaCollectorWorker.resources.limits.memory }}
            cpu: {{ .Values.digmaCollectorWorker.resources.limits.cpu }}
        env:
        {{- include "env.isCentralize" . | nindent  8 }}
        {{- include "env.licenseKey" . | nindent  8 }}
        {{- include "env.digmaEnv" . | nindent  8 }}
        {{- include "env.digmaSite" . | nindent  8 }}
        {{- include "env.otlpExporter" . | nindent  8 }}
        {{- include "env.otlpExportLogs" . | nindent  8 }}
        {{- include "env.otlpExportMetrics" . | nindent  8 }}
        {{- include "env.otlpExportTraces" . | nindent  8 }}
        {{- include "env.redis" . | nindent  8 }}
        {{- include "env.influx" . | nindent  8 }}
        {{- include "env.postgres" . | nindent  8 }}
        {{- include "env.kafka" . | nindent  8 }}
        {{- include "env.versions" . | nindent  8 }}
        {{- include "env.embeddedJaeger" . | nindent  8 }}
        {{- include "env.digmaEnvType" . | nindent 8 }}
        - name: BlockedTrace__TraceSpansLimit
          value: "3000"
        - name: OtlpSamplerProbability
          value: {{ .Values.digmaSelfDiagnosis.otlpSamplerProbability| quote}}
        - name: BACKEND_DEPLOYMENT_TYPE
          value: {{ .Values.deploymentType | quote}}
        - name: TraceTempStorage__TraceForJaegerExpirationInMinutes
          value: {{ .Values.digmaCollectorWorker.traceForJaegerTTL | quote }}
        - name: ExtendedObservability__Enable
          value: {{ .Values.digmaCollectorWorker.extendedObservability.enable | quote }}
        - name: Sampling__Enable
          value: {{ .Values.digmaCollectorWorker.sampling.enable | quote }}
        - name: ThresholdOptions__RecentActivityUpdateThresholdSeconds
          value: {{ .Values.traceCollectorThresholds.recentActivityUpdateThresholdSeconds | quote }}
        {{- range $index, $element := .Values.digmaCollectorWorker.ignoreEndpoints }}
        - name: Filter__IgnoreEndpoints__{{$index}}__Route
          value: {{ $element.Route | quote }}
        - name: Filter__IgnoreEndpoints__{{$index}}__RouteRegex
          value: {{ $element.RouteRegex | quote }}
        - name: Filter__IgnoreEndpoints__{{$index}}__Method
          value: {{ $element.Method | quote }}
        - name: Filter__IgnoreEndpoints__{{$index}}__Service
          value: {{ $element.Service | quote }}
        {{- end }}  