apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: {{ tpl .Values.kafka.host . }}
  template:
    metadata:
      labels:
        app: kafka
        {{- range $key, $value := .Values.kafka.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.kafka.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 5
      {{- include "imagePullSecrets" . | nindent  6 }}
      {{- include "tolerations" . | nindent  6 }}
      {{- include "nodeSelector" . | nindent  6 }}
      securityContext:
        fsGroup: 1001
      containers:
      - name: kafka
        image: bitnami/kafka:{{ .Values.kafka.imageTag }}
        imagePullPolicy: Always
        args:
          {{- range .Values.kafka.args }}
          - {{ . }}
          {{- end }}
        resources:
          requests:
            memory: {{ .Values.kafka.resources.requests.memory }}
            cpu: {{ .Values.kafka.resources.requests.cpu }}
          limits:
            memory: {{ .Values.kafka.resources.limits.memory }}
            cpu: {{ .Values.kafka.resources.limits.cpu }}
        ports:
        - containerPort: 9092
        volumeMounts: 
        - name: kafka-data
          mountPath: /bitnami/kafka
        env:
        # KRaft settings
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: h4U35I9QRnGhbgsEQAlXAw
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: controller,broker
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: 1@127.0.0.1:9093
        # Listeners
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092,CONTROLLER://:9093
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://{{ tpl .Values.kafka.host . }}:9092
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        # Retention
        - name: KAFKA_CFG_LOG_RETENTION_MINUTES
          value: "10"
        - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS
          value: "100000" # 1 min
        - name: KAFKA_CFG_LOG_ROLL_MS
          value: "500000" # 5 min
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 80Gi


