apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digma.global.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if include "digma.emailSettings.apiKey" . }}
  {{ include "digma.emailSettingsApiKey.secretKeyName" .}}: {{ include "digma.emailSettings.apiKey" . | b64enc | quote }}
  {{- end }}
  {{ include "digma.licenseKey.secretKeyName" .}}: {{ required "A valid .Values.digma.licenseKey entry is required. If you've signed up for a free Digma account you should have received a Digma license to use. check https://docs.digma.ai/digma-developer-guide/installation/central-on-prem-install" .Values.digma.licenseKey | b64enc | quote }}
  {{ include "digma.postgresqlPassword.secretKeyName" .}}: {{ include "digma.database.password" . | b64enc | quote }}
