{{- if (include "digma.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digma.secretName" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.digma.licenseKey }}
  license-key: {{ .Values.digma.licenseKey | b64enc }}
  {{- end }}
  {{- if .Values.digma.accessToken }}
  access-token: {{ .Values.digma.accessToken | b64enc }}
  {{- end }}
  {{- if .Values.digma.auth.password }}
  auth-password: {{ .Values.digma.auth.password | b64enc  }}
  {{- end }}
  {{- if include "digma.emailSettings.apiKey" . }}
  email-settings-api-key: {{ include "digma.emailSettings.apiKey" . | b64enc }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) .Values.digma.externals.postgresql.password }}
  postgres-password: {{ .Values.digma.externals.postgresql.password | b64enc }}
  {{- end }}
  {{ if and .Values.digma.socialLogin.enabled .Values.digma.socialLogin.google.secret }}
  social-login-google-secret: {{ .Values.digma.socialLogin.google.secret | b64enc }} 
  {{- end }}
  {{ if .Values.ui.postHogApiKey }}
  postHog-api-key: {{ .Values.ui.postHogApiKey | b64enc }}
  {{- end }}
  {{ if .Values.ui.productFruitsWorkspaceCode }}
  product-fruits-workspace-code: {{ .Values.ui.productFruitsWorkspaceCode | b64enc }}
  {{- end }}
{{- end }}