apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "digma.nginx" . }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: digma-nginx
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  nginx.conf: |
    {{  tpl (.Files.Get "files/nginx.conf") $ | nindent 4 }}