{{ if .Values.debug }}

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-debug
  labels:
    app/all-debug: ""
    app/pgadmin: ""
    app/redis-commander: ""
    app/kibana: ""
    app/elastic-apm-server: ""
spec:
  containers:

    - name: pgadmin
      image: dpage/pgadmin4
      volumeMounts:
      - name: pgadmin-data
        mountPath: /var/lib/pgadmin
      env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: {{ .Values.pgadmin.email }}
      - name: PGADMIN_DEFAULT_PASSWORD
        value: {{ .Values.pgadmin.password }}

    - name: redis-commander
      image: rediscommander/redis-commander:latest
      env:
      - name: REDIS_HOSTS
        value: {{ tpl .Values.redis.host . }}

    - name: elastic-apm-server
      image: docker.elastic.co/apm/apm-server:7.13.0
      securityContext:
        capabilities:
          add: [CHOWN, DAC_OVERRIDE, SETGID, SETUID]
          drop: [ALL]
      args:
      - apm-server
      - -e
      - -E
      - apm-server.rum.enabled=true
      - -E
      - setup.kibana.host=localhost:5601
      - -E
      - setup.template.settings.index.number_of_replicas=0
      - -E
      - apm-server.kibana.enabled=true
      - -E
      - apm-server.kibana.host=localhost:5601
      - -E
      - output.elasticsearch.hosts=[localhost:9200]

    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
      volumeMounts:
      - name: elasticsearch-data
        mountPath: /usr/share/elasticsearch/data
      env:
      - name: xpack.monitoring.enabled
        value: "true"
      - name: xpack.watcher.enabled
        value: "false"
      - name: ES_JAVA_OPTS
        value: -Xms512m -Xmx512m
      - name: discovery.type
        value: single-node

    - name: kibana
      image: docker.elastic.co/kibana/kibana:7.13.0
      env:
      - name: ELASTICSEARCH_HOSTS
        value: http://localhost:9200
      - name: xpack.apm.enabled
        value: "false"

  volumes:
    - name: pgadmin-data
      emptyDir: {}
    - name: elasticsearch-data
      emptyDir: {}

{{ end }}