apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_NAME
          value: postgres
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username}}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password}}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432 
      volumes:
      - name: postgres-data
        emptyDir: {}



     
     
