{{- if eq "true" (include "digma.observability.enabled" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "digma.k8s-metrics-exporter" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: k8s-metrics-exporter
rules:
- apiGroups: [""]
  resources: [pods]
  verbs: [list, get]
- apiGroups: [""]
  resources: [pods/exec]
  verbs: [create, get]
- apiGroups: ["apps"]
  resources: [deployments, statefulsets]
  verbs: [list]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: [list]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "digma.k8s-metrics-exporter" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: k8s-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "digma.k8s-metrics-exporter" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "digma.k8s-metrics-exporter" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}