apiVersion: v2
version: 1.0.0
name: digma-with-alb
home: https://github.com/digma-ai/helm-chart/examples/digma-with-alb
type: application
dependencies:
- name: digma
  version: 1.0.252
  repository: "https://digma-ai.github.io/helm-chart"
