apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digma.ui.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.ui.postHogApiKey }}
  {{ include "digma.ui.postHogApiKey.secretKeyName" .}}: {{ .Values.ui.postHogApiKey | b64enc }}
  {{- end }}
  {{- if .Values.ui.productFruitsWorkspaceCode }}
  {{ include "digma.ui.productFruitsWorkspaceCode.secretKeyName" .}}: {{ .Values.ui.productFruitsWorkspaceCode | b64enc }}
  {{- end }}


