apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "digma.ui" . }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  admin-env.js: |
    {{ .Files.Get "files/ui/admin/env.js" | tpl | indent 4 }}