{{ if .Values.observability.useLocal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digma.prometheus.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: prometheus
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data: 
  prometheus.yaml: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: otel-collector
        static_configs:
          - targets: [{{ include "digma.otel-collector-df-prometheus-scraper-url" .}}]
{{- end }}