{{ if .Values.observability.useLocal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: digma-grafana-redis-dashboards
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: digma-grafana-apps-dashboards
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  redis.json: |
    {{ .Files.Get "files/grafana-dashboards/Redis.json" | nindent 4 }}
{{- end }}