{{ if .Values.observability.useLocal }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource
type: Opaque
stringData:
    prometheus_datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: {{ include "digma.prometheus.url" .}}
        version: 1
        editable: true
        isDefault: true
        uid: prometheusdatasource
{{- end }}