annotations:
  category: Application
apiVersion: v2
appVersion: 0.3.323
dependencies:
- name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 31.0.0
- name: prometheus
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 1.3.28
  condition: observability.useLocal
- name: grafana
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 11.3.26
  condition: observability.useLocal
- name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 21.4.1
- name: elasticsearch
  version: 21.4.1
  repository: oci://registry-1.docker.io/bitnamicharts
  alias: elasticsearchlogs
  condition: elasticsearchlogs.enabled
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.3.0
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.2.1
- name: clickhouse
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 8.0.7
  condition: clickhouse.enabled
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
  tags:
  - bitnami-common
name: digma-ng
description: A Helm chart containing Digma's services
home: https://github.com/digma-ai/digma
icon: https://digma.ai/wp-content/uploads/2024/02/logo-alt-1.svg
type: application
version: 1.0.355
