{{ if .Values.ai.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "digma.ai" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ai
  {{- if or .Values.ai.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ai.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ai.service.type }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.ai.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ai
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.ai.service.ports.http }}
 {{- end }}