{
 "title": "Activities",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(activity_call_duration_ms_bucket,source_env)"
    }
   },
   {
    "name": "source",
    "label": "Activity Source",
    "query": {
     "query": "label_values(activity_calls_total,source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Activity Sources (click to filter)",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(activity_calls_total{source_env=\"$environment\", source=~\".+\"}) by (source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(activity_calls_total{source_env=\"$environment\", source=~\"$source\"}[5m])) by (source, name)",
     "legendFormat": "{{source}}.{{name}}"
    }
   ]
  },
  {
   "title": "Duration P95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(activity_call_duration_ms_bucket{source_env=\"$environment\", source=~\"$source\"}[5m])) by (le, source, name))",
     "legendFormat": "{{source}}.{{name}}"
    }
   ]
  },
  {
   "title": "Sum of Durations per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(activity_call_duration_ms_sum{source_env=\"$environment\", source=~\"$source\"}[5m])) by (source, name)",
     "legendFormat": "{{source}}.{{name}}"
    }
   ]
  }
 ]
}