{
 "title": "Apps System Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(activity_call_duration_ms_sum,source_env)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(kube_pod_cpu_usage,container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "100% = 1 Core",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_cpu_usage{source_env=\"$environment\", container=~\".*$app.*\"} unless rate(kube_pod_cpu_usage{source_env=\"$environment\", container=~\".*$app.*\"}[$__rate_interval]) == 0) by (pod)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_mem_usage{source_env=\"$environment\", container=~\".*$app.*\"} unless rate(kube_pod_mem_usage{source_env=\"$environment\", container=~\".*$app.*\"}[5m]) == 0) by (pod) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pvc_used_storage{source_env=\"$environment\", pod=~\".*$app.*\"}) by (pvc)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}