{
 "title": "Environment",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(activity_call_duration_ms_bucket,source_env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU & Memory Usage (last $__interval) by single pod",
     "type": "table",
     "gridPos": { "h": 17, "w": 14, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\r\n  avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"digma\"}[$__interval])\r\n* on(namespace,pod)\r\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"digma\"}\r\n) by (workload)\r\n\r\n"
      },
      {
       "expr": "max(\r\n  max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"digma\"}[$__interval])\r\n* on(namespace,pod)\r\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"digma\"}\r\n) by (workload)\r\n\r\n"
      },
      {
       "expr": "avg(\r\n  avg_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"digma\", container!=\"\", image!=\"\"}[$__interval])\r\n  * on(namespace,pod)\r\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"digma\"}\r\n) by (workload)"
      },
      {
       "expr": "max(\r\n  max_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"digma\", container!=\"\", image!=\"\"}[$__interval])\r\n  * on(namespace,pod)\r\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"digma\"}\r\n) by (workload)"
      }
     ]
    },
    {
     "title": "Disk Usage (last $__interval)",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\r\n  sum (avg_over_time(kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"digma\",}[$__interval])) by (persistentvolumeclaim)\r\n  -\r\n  sum (avg_over_time(kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"digma\"}[$__interval])) by (persistentvolumeclaim)\r\n)"
      },
      {
       "expr": "(\r\n  sum (min_over_time(kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"digma\",}[$__interval])) by (persistentvolumeclaim)\r\n  -\r\n  sum (min_over_time(kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"digma\"}[$__interval])) by (persistentvolumeclaim)\r\n)"
      }
     ]
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "100% = 1 Core",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_cpu_usage{source_env=\"$environment\"} unless rate(kube_pod_cpu_usage{source_env=\"$environment\"}[5m]) == 0) by (container)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_mem_usage{source_env=\"$environment\"} unless rate(kube_pod_mem_usage{source_env=\"$environment\"}[5m]) == 0) by (container) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pvc_used_storage{source_env=\"$environment\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "description": "100% = 1 Core",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_cpu_usage{source_env=\"$environment\"} unless rate(kube_pod_cpu_usage{source_env=\"$environment\"}[5m]) == 0) by ()",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_mem_usage{source_env=\"$environment\"} unless rate(kube_pod_mem_usage{source_env=\"$environment\"}[5m]) == 0) by ()",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pvc_used_storage{source_env=\"$environment\"}) by ()",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_restarts{source_env=\"$environment\"}[1m])>0) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_total_replicas{source_env=\"$environment\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Log Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "By App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(delta(log_error_count_total{source_env=\"$environment\"}[$__rate_interval])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By Logger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(delta(log_error_count_total{source_env=\"$environment\"}[$__rate_interval])) by (logger)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By Exception Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(delta(log_error_count_total{source_env=\"$environment\"}[$__rate_interval])) by (exceptionType)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traces & Spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Traces per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (env) (rate(request_traces_total{source_env=\"$environment\", env=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{digma_env}}"
    }
   ]
  },
  {
   "title": "Spans per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(request_spans_total{source_env=\"$environment\", env=~\".+\"}[$__rate_interval])) by (env)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(throttled_spans_total{source_env=\"$environment\"}[$__rate_interval])) by ()",
     "legendFormat": "{{label_name}} (throttled)"
    },
    {
     "expr": "sum(rate(blocked_spans_total{source_env=\"$environment\"}[$__rate_interval])) by ()",
     "legendFormat": "{{label_name}} (blocked)"
    }
   ]
  },
  {
   "title": "Spans per Second by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(request_spans_total{source_env=\"$environment\", env=~\".+\"}[$__rate_interval])) by (env, service)",
     "legendFormat": "{{env}} ({{service}})"
    }
   ]
  },
  {
   "title": "Alive Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "max_over_time(alive_traces_count{source_env=\"$environment\"}[$__rate_interval])>0",
     "legendFormat": "collector-worker-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Alive Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "max_over_time(alive_spans_count{source_env=\"$environment\"}[$__rate_interval])>0",
     "legendFormat": "collector-worker-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "max_over_time(soft_limit{source_env=\"$environment\"}[$__rate_interval])>0",
     "legendFormat": "limit-{{exported_instance}}"
    },
    {
     "expr": "max_over_time(items_count{source_env=\"$environment\"}[$__rate_interval])>0",
     "legendFormat": "size-{{exported_instance}}"
    },
    {
     "expr": "delta(items_added_total{source_env=\"$environment\"}[$__rate_interval])",
     "legendFormat": "added-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Influx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Influx requests total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(rate(influx_requests_total{source_env=\"$environment\"}[5m]))",
       "legendFormat": "{{query_name}}"
      }
     ]
    },
    {
     "title": "Influx requests by query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "sum(rate(influx_requests_total{source_env=\"$environment\"}[5m])) by (query_name)",
       "legendFormat": "{{query_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Jaeger Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Jaeger Exporter Trace/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(delta(jaeger_exporter_traces_size_kb_count{source_env=\"$environment\"}[5m])/5) by (caller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Exporter Upload/hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(delta(jaeger_exporter_traces_size_kb_sum{source_env=\"$environment\"}[2m])) by (le, caller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Exporter Spans/Trace P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jaeger_exporter_traces_spans_bucket{source_env=\"$environment\"}[5m])) by (le, caller))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka (Real/In-Memory)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Message in queue time (P95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_message_time_in_queue_bucket{source_env=\"$environment\"}[5m])) by (le, consumerGroupId))",
     "legendFormat": "{{ConsumerGroupId}}"
    }
   ]
  },
  {
   "title": "Message in queue time (P50)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(kafka_message_time_in_queue_bucket{source_env=\"$environment\"}[5m])) by (le, consumerGroupId))",
     "legendFormat": "{{consumer_type}}"
    }
   ]
  },
  {
   "title": "Messages in batch (P95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_messages_in_batch_bucket{source_env=\"$environment\"}[$__rate_interval])) by (le, consumerGroupId))",
     "legendFormat": "{{consumerGroupId}}"
    }
   ]
  }
 ]
}