{
 "title": "Kafka",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_consumer_group_lag_sum_ratio,source_env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Message Waiting Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kafka_message_time_in_queue_bucket{source_env=\"$environment\"}[5m])) by (le, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P75",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(kafka_message_time_in_queue_bucket{source_env=\"$environment\"}[5m])) by (le, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafka_message_time_in_queue_bucket{source_env=\"$environment\"}[5m])) by (le, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Message Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "P50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kafka_message_time_in_consumer_bucket{source_env=\"$environment\"}[5m])>0) by (le, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P75",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(kafka_message_time_in_consumer_bucket{source_env=\"$environment\"}[5m])>0) by (le, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafka_message_time_in_consumer_bucket{source_env=\"$environment\"}[5m])>0) by (le, topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Published Messages (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(delta(kafka_partition_current_offset_ratio{source_env=\"$environment\"}[5m])/5) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_group_lag_sum_ratio{source_env=\"$environment\"} unless rate(kafka_consumer_group_lag_sum_ratio{source_env=\"$environment\"}[5m]) == 0) by (topic) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed Messages (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumer_group_offset_sum_ratio{source_env=\"$environment\"}[5m])/5) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(kafka_topic_partitions{source_env=\"$environment\"}[7d])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partition distribution z-score",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "(\r\n    stddev (kafka_consumer_group_offset_ratio{source_env=\"$environment\"}) \r\n    by (group) \r\n    /\r\n    avg (kafka_consumer_group_offset_ratio{source_env=\"$environment\"}) \r\n    by (group) \r\n) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}