apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digma.otel-collector-df" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-collector-df
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
      kafkametrics:
        protocol_version: 2.0.0
        collection_interval: 10s
        brokers: [{{ printf "%s:9092" (tpl .Values.kafka.host .)}}]
        scrapers:
          - brokers
          - topics
          - consumers
      prometheus/k8s_metrics:
        config:
          scrape_configs:
            - job_name: k8s-metrics
              scrape_interval: 5s
              static_configs:
                - targets: [{{ include "digma.k8s-metrics-exporter-target" .}}]

    processors:
      batch:
      attributes/add_source_env:
        actions:
          - key: source_env
            value: {{.Values.digma.environmentName}}
            action: insert

    exporters:
      logging:
        verbosity: detailed
      {{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}
      prometheus:
        endpoint: 0.0.0.0:{{ .Values.otelCollectorDf.service.ports.prometheus_scraper }}
        send_timestamps: true
        metric_expiration: 10m
      {{- else }}
      otlp:
        endpoint: {{.Values.digmaSelfDiagnosis.otlpExporterEndpoint}}
      {{- end }}

    service:
      pipelines:
        {{- if eq .Values.digmaSelfDiagnosis.otlpExporterEndpoint "local" }}
        metrics:
          receivers: [otlp, kafkametrics, prometheus/k8s_metrics]
          processors: [attributes/add_source_env, batch]
          exporters: [prometheus]
        {{- else }}
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp, kafkametrics, prometheus/k8s_metrics]
          processors: [attributes/add_source_env, batch]
          exporters: [otlp]
        {{- end }}
