name: Lint Helm Charts

on: [push, pull_request]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            # Install kubeval
      - name: Install kubeval
        run: |
          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin
      - name: Helm dependency update
        run: |
            helm dependency update ./charts/digma-ng
      - name: Run Helm Lint
        run: |
          helm lint ./charts/digma-ng --set digma.licenseKey="dummy-license-key"
      # Validate YAML Syntax with yamllint
      # - name: Validate YAML Files
      #   uses: super-linter/super-linter@v7.2.0
      #   with:
      #     languages: "yaml"
      # Run kubeval for Kubernetes Manifest Validation
      - name: Validate Kubernetes Manifests
        run: |
          helm template ./charts/digma-ng | kubeval --strict
      
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1 
      # Optional: Dry run with a Kubernetes cluster
      - name: Dry Run Deployment
        run: |
          helm upgrade --install my-release ./charts/digma-ng --dry-run --debug --set digma.licenseKey="dummy-license-key"

