name: Lint Helm Charts - OLD Digma Chart

on:
  workflow_run:
    workflows: ["Validate PR"]
    types:
      - completed

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      # Install kubeval
      - name: Install kubeconform
        run: |
            curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xvzf - && \
            sudo mv kubeconform /usr/local/bin/ 
      - name: Run Helm Lint #validates the chart structure and Helm-specific syntax.
        run: |
          helm lint ./charts/digma --set digma.licenseKey="dummy-license-key"
      - name: Validate Kubernetes Manifests #ensuring templates render without errors, kubeconform validates the rendered manifests against Kubernetes API schemas, ensuring they are deployable
        run: | 
          set -e
          helm template my-release ./charts/digma --set digma.licenseKey="dummy-license-key" > output.yaml
          kubeconform -strict output.yaml