name: Lint Helm Charts

on: [pull_request]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.10.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          echo "Changed charts: $changed"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Install kubeconform
        if: steps.list-changed.outputs.changed == 'true'
        run: |
            curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xvzf - && \
            sudo mv kubeconform /usr/local/bin/ 
      - name: Helm dependency update
        if: steps.list-changed.outputs.changed == 'true'
        run: |
            helm dependency update ./charts/digma-ng
      - name: Run Helm Lint
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm lint ./charts/digma-ng \
            --set digma.licenseKey="dummy-license-key" \
            --set digma.auth.email="ci@example.invalid" \
            --set digma.auth.password="dummy-pass" \
            --set digma.accessToken="dummy-token"

      - name: Validate Kubernetes Manifests
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          set -e
          helm template my-release ./charts/digma-ng \
            --set digma.licenseKey="dummy-license-key" \
            --set digma.auth.email="ci@example.invalid" \
            --set digma.auth.password="dummy-pass" \
            --set digma.accessToken="dummy-token" \
          > output.yaml
          kubeconform -strict output.yaml
      # - name: Create k8s Kind Cluster # checking that resource dependencies are properly resolved (e.g., Secrets, ConfigMaps),close to real-world deployment.
      #   uses: helm/kind-action@v1 
      # - name: Dry Run Deployment
      #   run: |
      #     helm upgrade --install my-release ./charts/digma-ng --dry-run --debug --set digma.licenseKey="dummy-license-key"

