name: Lint Helm Charts

on: [push, pull_request]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Run Helm Lint
        run: |
          helm lint ./charts/digma --set digma.licenseKey="dummy-license-key"
      # Validate YAML Syntax with yamllint
      # - name: Validate YAML Files
      #   uses: super-linter/super-linter@v7.2.0
      #   with:
      #     languages: "yaml"
      # Run kubeval for Kubernetes Manifest Validation
      - name: Validate Kubernetes Manifests
        run: |
          helm template ./charts/digma --set digma.licenseKey="dummy-license-key" | kubeval --strict
      # Optional: Dry run with a Kubernetes cluster
      - name: Dry Run Deployment
        run: |
          helm upgrade --install my-release ./charts/digma --dry-run --debug --set digma.licenseKey="dummy-license-key"

