name: Lint Helm Charts

on: [pull_request]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.10.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          echo "Changed charts: $changed"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Setup kubectl
        if: steps.list-changed.outputs.changed == 'true'
        run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/ 
      - name: Helm dependency update
        if: steps.list-changed.outputs.changed == 'true'
        run: |
            helm dependency update ./charts/digma-ng
      - name: Run Helm Lint
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm lint ./charts/digma-ng \
            --set digma.licenseKey="dummy-license-key" \
            --set digma.auth.email="ci@example.invalid" \
            --set digma.auth.password="dummy-pass" \
            --set digma.accessToken="dummy-token"

      - name: Create k8s Kind Cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: validation-cluster
      - name: Install Strimzi CRDs
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          # Install Strimzi CRDs for proper validation
          kubectl create namespace strimzi-system
          kubectl apply -f https://strimzi.io/install/latest?namespace=strimzi-system
      - name: Validate Kubernetes Manifests
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          set -e
          # Full validation with real Kubernetes cluster and CRDs
          helm template my-release ./charts/digma-ng \
            --set digma.licenseKey="dummy-license-key" \
            --set digma.auth.email="ci@example.invalid" \
            --set digma.auth.password="dummy-pass" \
            --set digma.accessToken="dummy-token" \
          | kubectl apply --dry-run=server -f -


