name: Version Verifier

on: [pull_request]

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
     
      - name: Run Version Verifier Script
        run: python .github/script/version_verifier.py 'src/digma/Chart.yaml' 'rendered-deployment.yaml'

    